server/myapp/urls.py
from django.conf.urls import url

from . import views

app_name = 'myapp'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^category/search', views.search, name='search'),
    url(r'^category/(?P<cat_id>[0-9]+)/$', views.categories, name='category'),
    url(r'^category/(?P<cat_id>[0-9]+)/recipes/$', views.recipes, name='recipes'),
    url(r'^category/(?P<recipe_id>[0-9]+)/reviews/$', views.reviews, name='reviews'),
    url(r'^category/(?P<recipe_id>[0-9]+)/ingredients/$', views.ingredients, name='ingredients'),
    url(r'^category/(?P<recipe_id>[0-9]+)/instructions/$', views.instructions, name='instructions'),
    url(r'^category/(?P<recipe_id>[0-9]+)/review/(?P<review_id>[0-9]+)$', views.review, name='review'),
    url(r'^category/(?P<recipe_id>[0-9]+)/review/$', views.review, name='review'),
    url(r'^categories/?$', views.CatList.as_view()),
    url(r'^categories/(?P<pk>[0-9]+)/?$', views.CatDetail.as_view()),
    url(r'^recipes/?$', views.RecipeList.as_view()),
    url(r'^recipes/(?P<pk>[0-9]+)/?$', views.RecipeDetail.as_view()),
    url(r'^recipes/(?P<recipe_id>[0-9]+)/reviews/?$', views.ReviewList.as_view()),
    url(r'^recipes/(?P<recipe_id>[0-9]+)/ingredients/?$', views.IngrList.as_view()),
    url(r'^recipes/(?P<recipe_id>[0-9]+)/ingredients/search/?$', views.ingredients),
    url(r'^recipes/(?P<recipe_id>[0-9]+)/instructions/?$', views.InstrList.as_view()),
    url(r'^recipes/(?P<recipe_id>[0-9]+)/reviews/(?P<pk>[0-9]+)/?$', views.ReviewDetail.as_view()),
]

server/myproject/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.http.response import HttpResponseRedirect
from rest_framework_jwt.views import obtain_jwt_token
from myapp import views

urlpatterns = [
    url(r'^api/', include('myapp.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^api-auth/', include('rest_framework.urls')),
    url(r'^api-token-auth/', obtain_jwt_token),
    url(r'^$', lambda r: HttpResponseRedirect('api/')),
]

urlpatterns += url(r'^(?P<path>.*)$', views.index2),

server/myapp/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import AbstractUser

class Ingredient(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name;

class Recipe(models.Model):
    title = models.CharField(max_length=200)
    calories = models.IntegerField('Calories')
    ingredients = models.ManyToManyField(Ingredient, default="")

    def __str__(self):
        return "%s %s" % (self.title, self.calories)

class Description(models.Model):
    name = models.TextField(max_length=5000, default="")
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)

    def __str__(self):
        return self.name;

class Category(models.Model):
    name = models.CharField(max_length=200)
    recipes = models.ManyToManyField(Recipe)

    def __str__(self):
        return self.name;

class Review(models.Model):
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = models.TextField(default="")
    review_date = models.DateTimeField('review date')

server/myapp/views.py
from django.shortcuts import render, get_object_or_404
from django.http import *
from .models import Recipe, Category, Review, Description, Ingredient
from django.urls import reverse
from django.utils import timezone
from .serializers import RecipeSerializer, ReviewSerializer, CatSerializer, InstrSerializer, IngrSerializer
from rest_framework import generics
from django.contrib.staticfiles import views

from rest_framework import permissions

def index(request):
    cat_all = Category.objects.order_by('name')
    ing_all = Ingredient.objects.order_by('name')
    context = {'cat_all': cat_all, 'ing_all': ing_all}
    return render(request, 'myapp/index.html', context)

def index2(request, path=''):
    if (path.endswith('.js')):
        return views.serve(request, path)
    else:
        return views.serve(request, 'index.html')

class RecipeList(generics.ListCreateAPIView):
    serializer_class = RecipeSerializer

    def get_queryset(self):
        queryset = Recipe.objects.all()
        title = self.request.query_params.get('title', None)
        if title is not None:
            queryset = queryset.filter(title__icontains=title)
        return queryset

class RecipeDetail(generics.RetrieveUpdateDestroyAPIView):
    queryset = Recipe.objects.all()
    serializer_class = RecipeSerializer

class ReviewList(generics.ListCreateAPIView):
    serializer_class = ReviewSerializer
    permission_classes = (permissions.IsAuthenticatedOrReadOnly,)

    def get_queryset(self):
        queryset = Review.objects.all()
        recipe_id = self.kwargs.get('recipe_id', None)
        if recipe_id is not None:
            queryset = queryset.filter(recipe=recipe_id)
        return queryset

class ReviewDetail(generics.RetrieveUpdateDestroyAPIView):
    queryset = Review.objects.all()
    serializer_class = ReviewSerializer
    permission_classes = (permissions.IsAuthenticatedOrReadOnly,)

class CatList(generics.ListCreateAPIView):
    serializer_class = CatSerializer

    def get_queryset(self):
        queryset = Category.objects.all()
        cat_id = self.kwargs.get('cat_id', None)
        if cat_id is not None:
            queryset = queryset.filter(category=cat_id)
        return queryset

class CatDetail(generics.RetrieveUpdateDestroyAPIView):
    queryset = Category.objects.all()
    serializer_class = CatSerializer

def categories(request, cat_id):
    cat = get_object_or_404(Category, pk=cat_id)
    return render(request, 'myapp/recipes.html', {'cat': cat})

def recipes(request, cat_id):
    cat = get_object_or_404(Category, pk=cat_id)
    return render(request, 'myapp/reviews.html', {'cat': cat })
    #return HttpResponse("You are looking at category %s." % cat_id)

def ingredients(request, recipe_id=None):
    recipe = get_object_or_404(Recipe, pk=recipe_id)
    return render(request, 'myapp/ingredients.html', {'recipe': recipe })

class IngrList(generics.ListCreateAPIView):
    serializer_class = IngrSerializer

    def get_queryset(self):
        queryset = Ingredient.objects.all()
        recipe_id = self.kwargs.get('recipe_id', None)
        if recipe_id is not None:
            queryset = queryset.filter(recipe=recipe_id)
        return queryset

def instructions(request, recipe_id):
    instr = Description.objects.filter(recipe_id=recipe_id)
    return render(request, 'myapp/instructions.html', {'instr': instr })

class InstrList(generics.ListCreateAPIView):
    serializer_class = InstrSerializer

    def get_queryset(self):
        queryset = Description.objects.all()
        recipe_id = self.kwargs.get('recipe_id', None)
        if recipe_id is not None:
            queryset = queryset.filter(recipe=recipe_id)
        return queryset
def reviews(request, recipe_id):
    rec_reviews = Review.objects.filter(recipe_id=recipe_id)
    return render(request, 'myapp/reviews.html', {'rec_reviews': rec_reviews })

def review(request, recipe_id, review_id=None):
    if review_id is not None:
        review = get_object_or_404(Review, pk=review_id)
    else:
        review = Review()
        review.recipe_id = recipe_id
    if request.method == 'POST':
        review.title = request.POST['title']
        review.text = request.POST['text']
        review.review_date = timezone.now()
        review.save()
        return HttpResponseRedirect(reverse('myapp:reviews', args=(recipe_id,)))
    else:
        context = {
        'recipe_id': recipe_id,
        'review_id': review_id,
        'title': review.title,
        'text': review.text
    }
    return render(request, 'myapp/review.html', context)

def search(request):
    form = request.POST.getlist('item')
    recipe = Recipe.objects.all()
    recipeList = []
    print(form)
    for i in recipe:
        li = []
        ing = Ingredient.objects.filter(id=i.id)
        for j in form:
            for k in ing:
                print(j, k)
                if (str(k) == str(j)):
                    li.append(j)
        if (len(form) != 0 and set(form) <= set(li)):
            recipeList.append(i)

    return render(request, 'myapp/search.html', {'recipeList': recipeList })

server/myapp/templates/myapp/base.html
<!DOCTYPE html>
<html lang="en">
  <head>

    <!-- Required meta tags for Bootstrap -->
    <meta charset="utf-8">
    <meta name="viewport"
          content="width=device-width, initial-scale=1,
          shrink-to-fit=no">

    <!-- Bootstrap CSS -->

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet"
          href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css"
          integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M"
          crossorigin="anonymous"/>

    <title>{% block title %}Thought For Food{% endblock %}</title>
  </head>

  <body>
    <div class="container">
      <div class="jumbotron">
        <h1>{% block heading %}Thought For Food{% endblock %}</h1>
      </div>
      <div class="col-md-offset-1 col-md-6">
        {% block content %}{% endblock %}
      </div>
    </div>

    <!-- Optional JavaScript for Bootstrap -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
            integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js"
            integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4"
            crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js"
            integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1"
            crossorigin="anonymous"></script>
  </body>
</html>

server/myapp/templates/myapp/index.html
{% extends "myapp/base.html" %}

{% block content %}
<h4> Categories </h4>
{% if cat_all %}
  <ul class="list-group">
    {% for cat in cat_all %}
      <li class="list-group-item">
        <a href= "{% url 'myapp:category' cat.id %}">{{ cat.name }}</a>
      </li>
    {% endfor %}
  </ul>
{% else %}
  <p>No categories are available.</p>
{% endif %}

<h4> Ingredients </h4>
{% if ing_all %}
<form action="{% url 'myapp:search' %}" method="POST">
    {% csrf_token %}
    <div class="form-group">
    {% for i in ing_all %}
      <li>
        <input type="checkbox" name="item" value="{{ i.name }}">{{ i.name }}
      </li>
    {% endfor %}
    </div>
    <button type="submit" class="btn btn-primary">Search</button>
</form>
{% else %}
  <p>No Ingredients are available.</p>
{% endif %}
{% endblock %}

server/myapp/templates/myapp/ingredients.html
{% extends "myapp/base.html" %}

{% block content %}
{% if not recipe %}
  <h2 class="bg-warning">No ingredients yet.</h2>
{% else %}
<p> If you don't have all the ingredients, check those you do and then click Search to recommend you recipes according to the ingredients you have!</p>
<form action="{% url 'myapp:search' %}" method="POST">
    {% csrf_token %}
    <div class="form-group">
        Ingredients:
        {% for ing in recipe.ingredients.all %}
          <li>
            <input type="checkbox" name="item" value="{{ ing.name }}">{{ ing }}
          </li>
        {% endfor %}
    </div>
    <button type="submit" class="btn btn-primary">Search</button>
    <a class="btn btn-primary" href="{% url 'myapp:instructions' recipe.id %}">Go to instructions</a>
</form>

{% endif %}
{% endblock %}

server/myapp/templates/myapp/instructions.html
{% extends "myapp/base.html" %}

{% block content %}
{% if not instr %}
  <h2 class="bg-warning">No instructions yet.</h2>
{% else %}
  <div class="list-group">
    Instructions:
    {% for i in instr %}
      <li>
        {{ i.name }}
      </li>
    {% endfor %}
  </div>
{% endif %}
{% endblock %}

server/myapp/templates/myapp/recipes.html
{% extends "myapp/base.html" %}

{% block content %}
{% if not cat %}
  <h2 class="bg-warning">No recipes yet.</h2>
{% else %}
  Recipes:
  <ul class="list-group">
    <li class="list-group-item">
      <ul>
        {% for rec in cat.recipes.all %}
          <li>
            {{ rec.title }}
          </li>
          <li class="list-group-item">
            <span>Reviews:
            <a href="{% url 'myapp:reviews' rec.id %}">
              <span class="badge badge-secondary">{{ rec.review_set.all.count }}</span>
          </a>
            <a href="{% url 'myapp:review' rec.id %}">
              <span class="badge badge-secondary" aria-hidden="true">+</span>
            </a>
            </span>
          </li>
          <li class="list-group-item">
            <span>Ingredients:
            <a href="{% url 'myapp:ingredients' rec.id %}">
              <span class="badge badge-secondary">→</span>
            </a>
            </span>
          </li>
          <li class="list-group-item">
            <span>Instructions:
            <a href="{% url 'myapp:instructions' rec.id %}">
              <span class="badge badge-secondary">→</span>
            </a>
            </span>
          </li>
        {% endfor %}
      </ul>
    </li>
  </ul>
{% endif %}
{% endblock %}

server/myapp/templates/myapp/review.html
{% extends "myapp/base.html" %}

{% block content %}
{% if review_id %}
<form action="{% url 'myapp:review' recipe_id review_id %}"  method="post">
{% else %}
<form action="{% url 'myapp:review' recipe_id %}"  method="post">
{% endif %}
  {% csrf_token %}
    <div class="form-group">
    <label for="title">Title</label>
    <input type="text" id="title" name="title"
           class="form-control" placeholder="Title" value="{{ title }}"/>
  </div>
  <div class="form-group">
    <label for="text">Content</label>
    <textarea id="text" name="text"
              class="form-control" placeholder="content" rows="10">{{ text }}
    </textarea>
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock %}

server/myapp/templates/myapp/reviews.html
{% extends "myapp/base.html" %}

{% block content %}
{% if not rec_reviews %}
  <h2 class="bg-warning">No reviews yet.</h2>
{% else %}
  <div class="list-group">
    {% for review in rec_reviews %}
      <div class="list-group-item active">
        Summary: {{ review.title }}
      </div>
      <div class="list-group-item">
        Review: {{ review.text }}
      </div>
      <div class="list-group-item">
        Date reviewed: {{ review.review_date }}
      </div>
    {% endfor %}
  </div>
{% endif %}
{% endblock %}

server/myapp/templates/myapp/search.html
{% extends "myapp/base.html" %}

{% block content %}
{% if not recipeList %}
  <h2 class="bg-warning">No recipes matching.</h2>
{% else %}
    <div class="form-group">
        Recipes:
        {% for i in recipeList %}
          <li>
            {{ i.title }}: {{ i.calories }} calories
          </li>
          <li class="list-group-item">
                <span>Reviews:
                <a href="{% url 'myapp:reviews' i.id %}">
                  <span class="badge badge-secondary">{{ i.review_set.all.count }}</span>
              </a>
                <a href="{% url 'myapp:review' i.id %}">
                  <span class="badge badge-secondary" aria-hidden="true">+</span>
                </a>
                </span>
              </li>
              <li class="list-group-item">
                <span>Ingredients:
                <a href="{% url 'myapp:ingredients' i.id %}">
                  <span class="badge badge-secondary">→</span>
                </a>
                </span>
              </li>
              <li class="list-group-item">
                <span>Instructions:
                <a href="{% url 'myapp:instructions' i.id %}">
                  <span class="badge badge-secondary">→</span>
                </a>
                </span>
          </li>
        {% endfor %}
    </div>
</form>
{% endif %}
{% endblock %}